### ISSUE TITLE
meteor add gouthamve:reaction-razorpay

### ISSUE THREAD

**Issue by mayankamencherla** [Gouthamve/reaction-razorpay#1]
When I run this command on my reaction directory, I get the following errors:

MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

/Users/mayankamencherla/.meteor/packages/meteor-tool/.1.4.2_1.3msdi1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
abort() at Error
    at jsStackTrace (packages/logic-solver.js:22:18626)
    at stackTrace (packages/logic-solver.js:22:18809)
    at abort (packages/logic-solver.js:52:28956)
    at enlargeMemory (packages/logic-solver.js:22:19142)
    at Function.Runtime.dynamicAlloc [as alloc] (packages/logic-solver.js:22:7927)
    at _sbrk (packages/logic-solver.js:22:58803)
    at Sd (packages/logic-solver.js:26:98389)
    at Ud (packages/logic-solver.js:26:109800)
    at nc (packages/logic-solver.js:26:45266)
    at Yb (packages/logic-solver.js:26:27525)
    at Zb (packages/logic-solver.js:26:29119)
    at _b (packages/logic-solver.js:26:30575)
    at $b (packages/logic-solver.js:26:35130)
    at Bc (packages/logic-solver.js:26:54870)
    at Object.hd [as _solveAssuming] (packages/logic-solver.js:26:84479)
    at [object Object].MiniSat.solveAssuming (packages/logic-solver.js:157:18)
    at [object Object].Logic.Solver.solve (packages/logic-solver.js:1681:33)
    at [object Object].Logic.Solver.solveAssuming (packages/logic-solver.js:1714:21)
    at minMaxWS (packages/logic-solver.js:2000:32)
    at [object Object].Logic.Solver.minimizeWeightedSum (packages/logic-solver.js:2087:10)
    at packages/constraint-solver.js:1326:28
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object].CS.Solver.minimize (packages/constraint-solver.js:1310:16)
    at [object Object].CS.Solver.minimize (packages/constraint-solver.js:1304:10)
    at [object Object].CS.Solver._getAnswer (packages/constraint-solver.js:1693:8)
    at packages/constraint-solver.js:1561:17
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object].CS.Solver.getAnswer (packages/constraint-solver.js:1560:23)
    at packages/constraint-solver.js:2258:25
    at Object.Logic.disablingAssertions (packages/logic-solver.js:390:12)
    at Function.CS.PackagesResolver._resolveWithInput (packages/constraint-solver.js:2257:16)
    at [object Object].CS.PackagesResolver.resolve (packages/constraint-solver.js:2221:34)
    at /tools/project-context.js:518:35
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/project-context.js:514:19
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:486:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._resolveConstraints (/tools/project-context.js:485:13)
    at /tools/project-context.js:268:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
    at /tools/project-context.js:250:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
    at /tools/cli/commands-packages.js:2038:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Command.func (/tools/cli/commands-packages.js:2037:27)
    at /tools/cli/main.js:1483:23
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by brent-hoover** [comment]
Packages like this have been deprecated and will no longer work with Reaction Commerce.

**Comment by mayankamencherla** [comment]
So basically, this package is no longer working on Reaction Commerce?

Also, how can I add a package to the dashboard on my admin panel on Reaction Commerce? Do I just add it to my imports directory?

**Comment by brent-hoover** [comment]
I am not sure this package ever actually worked, I think it was a WIP but now it will no longer work as it needs to be re-written to be a plugin rather than a package.

I'd be happy to answer any more questions you have in our [gitter](https://gitter.im/reactioncommerce/reaction?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel.
